languages = ('Python', 'Java', 'C++')
length = len(languages)
print(length)
number = (1)
print(number)
number = (1,)
print(number)
number = ()
print(number)
number = (1,3,4,5)
print(number)
print('Python' in languages)
